services:
  - type: web
    name: traffic-light-detection
    env: python
    plan: starter
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
        value: python
      - key: PYTHON_VERSION
        value: 3.7
    healthCheckPath: /health
    autoDeploy: true
